### ISSUE TITLE
08.04짜 이슈

### ISSUE THREAD

**Issue by choihuk** [tlarbals824/StudentInformation#10]
- memberRepositoryTest에서 테스트하는 목적이 db에 잘 반영됐는지를 확인하는거니까 엔티티 매니저 불러와서 지운다음 다시 받는걸로 바꿈 -> 새로 받은 객체는 참조값이 다르니 동등성을 확인하려고 엔티티에 @EqualsAndHashCode 넣음 -> 양방향 참조이기에 처음  member 생성시 리스트엔 널 값이 들어가는데 jpa로 받은 객체는 널 값이 아닌 빈 리스트가 반환되므로 둘이 다른 객체로 반환됨 -> 엔티티들 생성자에 oneToMany 리스트 초기화함(빈 배열)

- memberServiceTest에서 맴버 정보 업데이트부분 우리가 확인하고 싶은게 db에 업데이트가 됐는지를 알고 싶은거라 생각해서 영속성 컨택스트 초기화하고 db에서 찾아오는걸로 바꿔봤는데 이렇게 테스트하는게 좋을까?

- 우리 offsettime으로 타임과 타임존 저장했는데 db에 저장됐다 다시 받으면 타임존이 달라지더라..? 이거 어캐 처리하지?
https://www.baeldung.com/mysql-jdbc-timezone-spring-boot
위에꺼 설정하면 될 것 같은데 안 되네.. 이거땜에 몇시간을 날린거야 슈밤

**Comment by tlarbals824** [comment]
MemberService 확인 바람

**Comment by tlarbals824** [comment]
에초에 우리는 DB에 저장되는게 말이 안됨

**Comment by tlarbals824** [comment]
테스트는 격리해야지

**Comment by tlarbals824** [comment]
그래서 transactional로 격리한거임

**Comment by tlarbals824** [comment]
그리고 이미 완성된 spring data jpa에서 repositorytest 만들 이유 모르곗음

**Comment by tlarbals824** [comment]
비밀번호 찾기_예외처리에서 테스트 코드를 하나다 작성하는게 의문임

**Comment by tlarbals824** [comment]
그리고 멤버추가method에서 findbyid까지 쓸필요 없어보임
