### ISSUE TITLE
LectureServiceTest 작성함, 페이징 기능 추가함

### ISSUE THREAD

**Issue by tlarbals824** [tlarbals824/StudentInformation#13]
아직 중복코드는 안걷어냄, 가독성이 좀 떨어지기는 해도 함 봐봐
그리고 생각해보니까 검색기능 쓸떄 교수님이름, 강의이름, 학기 중 하나만 이용해서 검색할 떄도 있긴한데
셋다 이용해서 검색할 수도 있으니까 나중에 3개다 이용해서 검색하게 메서드 하나 더 추가해둘게

**Comment by choihuk** [comment]
3개 다 검색하는건 우리 학교는 지원하지 않긴 한데 넣고 만들려면 이 UI 말고 다르게 만들어야 될 듯?
<img width="1418" alt="스크린샷 2022-08-08 오전 10 32 35" src="https://user-images.githubusercontent.com/39454230/183321512-e40b8a64-2e04-4631-a894-f5157299b99f.png">
 
페이징 기능 추가 잘 했네 가독성 좋은데..?

질문사항: lectureservice에서 나중에 쿼리 최적화한다는 뜻이 repository단에서 리스트로 받아오던걸  페이징 쿼리 날려서 

 -> Page<Member> findByAge(int age, Pageable pageable); 이런 식으로

받아오는걸로 바꿀 것이라는게 맞음?

**Comment by tlarbals824** [comment]
그러면 학기+교수님이름, 학기+강좌번호,학기+강의이름 이렇게하자


그리고 쿼리 최적화하는게 동적쿼리 직접짜서 날리는거 지금 사용하는 방식이 쿼리가 너무 많이 나가는듯, 다 긁어오는거라
물론 교수님이랑 강의수가 엄청 많지는 않아서 괜찮긴한데 그래도 나중에 최적화하면 좋을 듯

**Comment by choihuk** [comment]
ㅇㅋㅇㅋ 강의 검색 그렇게 하자

ㅇㅇ 다 긁어오는거라 최적화하면 좋을 것 같음. 나는 동적쿼리로 짜지 않고 repository에서 findByStateWithPage같은 page를 파라미터에 넣어줘서 반환값을 page로 받는 형식으로 짜면 스프링 데이터 jpa가 limit를 넣어줘서 일부만 긁어오니 최적화될 것 같은데 너 생각은 어떰?

**Comment by tlarbals824** [comment]
오 낟밷 그러면 나중에 바꿔둠
