### ISSUE TITLE
비즈니스 로직에 맞추어 uri 정하기

### ISSUE THREAD

**Issue by choihuk** [tlarbals824/StudentInformation#16]
<h3>User CRUD</h3>
<table>
<th>URL</th><th>요청</th><th>설명</th>

<tr>
<td>/members/login</td>
<td>GET</td>
<td>로그인 창 가져오기</td>
</tr>

<tr>
<td>/members/login</td>
<td>POST</td>
<td>로그인 창에서 로그인 버튼 누를 경우</td>
</tr>

<tr>
<td>/members/find-member</td>
<td>GET</td>
<td>아이디, 비밀번호 찾기 창 가져오기</td>
</tr>

<tr>
<td>/members/find-id</td>
<td>POST</td>
<td>아이디, 비밀번호 찾기 창에서 아이디 찾기 버튼 누를 경우</td>
</tr>

<tr>
<td>/members/find-password</td>
<td>POST</td>
<td>아이디, 비밀번호 찾기 창에서 비밀번호 찾기 버튼 누를 경우</td>
</tr>

<tr>
<td>/members/logout</td>
<td>GET</td>
<td>myInfo에서 로그아웃 버튼을 누를 경우</td>
</tr>

<tr>
<td>/members/password</td>
<td>GET</td>
<td>비밀번호 변경 창 가져오기</td>
</tr>

<tr>
<td>/members/password</td>
<td>POST</td>
<td>비밀번호 변경 창에서 변경 버튼을 누를 경우</td>
</tr>

<tr>
<td>/members/logout</td>
<td>GET</td>
<td>로그아웃 후 로그인 창으로 이동</td>
</tr>
</table>

<h3>Admin CRUD</h3>
<table>
<th>URL</th><th>요청</th><th>설명</th>

<tr>
<td>/admin</td>
<td>GET</td>
<td>어드민 전용 창 가져오기</td>
</tr>

<tr>
<td>/admin</td>
<td>POST</td>
<td>어드민 창에서 회원가입 버튼을 누를 경우</td>
</tr>
</table>

<h3>Lecture CRUD</h3>
<table>
<th>URL</th><th>요청</th><th>설명</th>

<tr>
<td>/lectures</td>
<td>GET</td>
<td>강의 개설 및 수정 창 가져오기(교수님 전용)</td>
</tr>

<tr>
<td>/lectures/new</td>
<td>POST</td>
<td>강의 개설</td>
</tr>

<tr>
<td>/lectures/{id}/edit</td>
<td>GET</td>
<td>강의 수정 창 가져오기</td>
</tr>

<tr>
<td>/lectures/{id}/edit</td>
<td>POST</td>
<td>강의 수정</td>
</tr>

<tr>
<td>/lectures/{id}/delete</td>
<td>POST</td>
<td>강의 삭제</td>
</tr>

<tr>
<td>/lectures/my</td>
<td>GET</td>
<td>내 강의 창 가져오기</td>
</tr>

<tr>
<td>/lectures/opened</td>
<td>GET</td>
<td>개설 강의 창 가져오기</td>
</tr>

<tr>
<td>/lectures/opened</td>
<td>POST</td>
<td>개설 강의 검색</td>
</tr>
</table>

<h3>Application CRUD</h3>
<table>
<th>URL</th><th>요청</th><th>설명</th>

<tr>
<td>/applications</td>
<td>GET</td>
<td>수강신청 창 가져오기</td>
</tr>

<tr>
<td>/applications</td>
<td>POST</td>
<td>선택한 강의 수강신청</td>
</tr>
</table>

<h3>Grade CRUD</h3>
<table>
<th>URL</th><th>요청</th><th>설명</th>

<tr>
<td>/grades</td>
<td>GET</td>
<td>성적 입력/수정 창 가져오기(교수님 전용)</td>
</tr>

<tr>
<td>/grades</td>
<td>POST</td>
<td>자신이 개설한 강의 선택 시 학생들 리스트 반환</td>
</tr>

<tr>
<td>/grades/{id}</td>
<td>GET</td>
<td>학생들 리스트가 추가된 성적 입력/수정 창 가져오기</td>
</tr>

<tr>
<td>/grades/{id}</td>
<td>POST</td>
<td>학생들 성적 입력/수정 내용 저장</td>
</tr>

<tr>
<td>/grades/my</td>
<td>GET</td>
<td>수강성적 조회 창 가져오기(학생 전용)</td>
</tr>

<tr>
<td>/grades/objection</td>
<td>GET</td>
<td>성적 이의신청 창 가져오기(학생 전용)</td>
</tr>

<tr>
<td>/grades/objection</td>
<td>POST</td>
<td>이의신청 전송</td>
</tr>

<tr>
<td>/grades/objection-list</td>
<td>GET</td>
<td>성적 이의신청 목록 창 가져오기(교수님 전용)</td>
</tr>

<tr>
<td>/grades/objection-list</td>
<td>POST</td>
<td>자신이 개설한 강의를 선택하면 해당 강의 이의신청 목록 띄우기</td>
</tr>

<tr>
<td>/grades/objection-list/{id}</td>
<td>GET</td>
<td>선택한 이의신청 창 가져오기(교수님 전용)</td>
</tr>

<tr>
<td>/grades/objection-list/{id}</td>
<td>POST</td>
<td>이의신청 결과 반환(승인여부, 성적)</td>
</tr>
</table>

**Comment by choihuk** [comment]
1. 앞에 member를 꼭 붙여야할까?
2. admin이 휴학, 전과 수정하는건 한 창 안에서 관리할까 아님 나눌까?

**Comment by tlarbals824** [comment]
일단 member 넣자
그러는게 관리하기 좋을듯

**Comment by tlarbals824** [comment]
admin이 관리하는거 한페이지 안에 관리하고 불편하면 분리하자 그게 편할듯
그리고 로그아웃 get으로 하면 될듯

**Comment by choihuk** [comment]
ㅇㅋㅇㅋ 계속 추가할테니 피드백 부탁

**Comment by choihuk** [comment]
내가 생각하는 어드민이 학생 정보 변경하는건 학생 이름을 selectbox로 다 뽑고 하나 선택하면 쿼리날려서 해당 학생의 정보(대학, state 등)을 수정 가능한 리스트 형식으로 보여준 뒤 수정 완료 누르면 현재 입력된 정보가 덮이는 형식으로 하고싶은데 어떰?
ㄴ 이 형식으로 하면 memberservice의 update 메서드를 그냥 사용하는게 휴학, 전과 메서드로 나누는 것보다 더 나아짐
ㄴ 학생이 많아지면 selectbox로 선택하는게 어려워질 수 있긴 함. 검색으로 해야되나
