### ISSUE TITLE
OffsetTime을 LocalTime과 int 타입으로 나누는 방안

### ISSUE THREAD

**Issue by choihuk** [tlarbals824/StudentInformation#18]
1. db에 저장 시 mysql은 time과 offset을 한꺼번에 저장할 데이터 타입이 없음
2. view에서 데이터를 가져와 dto 객체 필드에 넣을 때 form input 태그에 offset과 time을 한꺼번에 받을 타입이 없음
3. 학점 계산할 때 offsetTime에서 offset만 빼기 귀찮음. getOffset하면 앞에 +가 붙어서 떼어줘야함

결론: LocalTime으로 강의 시작 시간 저장하고 int credit(학점)타입으로 강의 몇 시간인지 저장하는건 어떰?

**Comment by tlarbals824** [comment]
아니면 그냥 localtime 말고 List<String>으로 강의 시간을 월34 화6 이렇게하는거 어떰 week도 걷어내고

**Comment by choihuk** [comment]
지금 week가 한 개 밖에 못받아서 문제긴 한데 week랑 time을 합치면 뷰에서 받을 때 한 필드에 같이 받는 법을 잘 모르겠음
물론 string으로 검증 제약하면 되긴 한데 리스트를 한꺼번에 받는거도 생각해야돼서 오히려 복잡할지도?
