### ISSUE TITLE
entity에 연관관계 메서드 추가

### ISSUE THREAD

**Issue by choihuk** [tlarbals824/StudentInformation#5]
양방향 연관관계로 설정하면 감수해야 되는 부분
---(jpashop의 order entity 참고)

**Comment by tlarbals824** [comment]
아 맞다 이거 생각안하고 있었음 바로 수정함

**Comment by tlarbals824** [comment]
수정함 한번 확인 해봐봐

**Comment by tlarbals824** [comment]
application은 수강 신청/취소
lecture도 교수님이 강의만들고 없애는거 뿐이니까, 교수님은 안바꿔서 중복체크는 뺌

**Comment by choihuk** [comment]
내일 안과 다녀와서 확인할게연
