### ISSUE TITLE
MemberService Test 작성헀으니까 한번 봐주삼

### ISSUE THREAD

**Issue by tlarbals824** [tlarbals824/StudentInformation#9]
exception 발생할떄도 테스트 해봄
테스트 작성할때 격리 방법 어칼까
이번에는 Transactional이용해서 rollback했는데 실무때랑 느낌이 달라서 고민중

**Comment by tlarbals824** [comment]
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)

테스트 양이 작으면 이거 써도 될듯

**Comment by choihuk** [comment]
transactional 사용해도 엔티티매니저 불러와서 영속성 컨택스트 초기화하면 해결할 수 있을 것 같아서 afterEach 사용하긴 함.
- DirtesContext 사용하는것도 좋은 생각임. 추후에 추가하는것도 충분히 고려해 볼만함.

**Comment by tlarbals824** [comment]
사실 영속상태 엔티티보다는 DB에 저장되는 엔티티들이 문제여서 영속성컨택스트를 초기화해도 별의미 없을듯

**Comment by tlarbals824** [comment]
findpassword도 중복되네

**Comment by tlarbals824** [comment]
예외처리 메서드에 경우에는 메서드 이름으로 충분히 커버 가능 하니까Displayname불필요할듯

**Comment by tlarbals824** [comment]
테스트 멤버추가테스트에서 변수를 추가하면서까지 테스트를 검증할필요는 없어보임
